name: Codacy Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '17 9 * * 2'

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 更新到最新版 checkout

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
          # 排除可能包含编码问题的文件/目录（根据项目实际情况调整）
          exclude: |
            **/docs/**
            **/vendor/**
            **/public/static/**
            **/*.md  # 排除 Markdown 文件（常含特殊字符）

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3  # 更新到最新版
        with:
          sarif_file: results.sarif
